# Generated by Django 4.2.7 on 2024-04-05 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.CharField(
                        choices=[
                            ("교육관", "교육관"),
                            ("대강당", "대강당"),
                            ("신세계관", "신세계관"),
                            ("생활관", "생활관"),
                            ("정문", "정문"),
                            ("포스코관", "포스코관"),
                            ("학문관", "학문관"),
                            ("휴웃길", "휴웃길"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("음식", "음식"),
                            ("굿즈", "굿즈"),
                            ("체험", "체험"),
                            ("기타", "기타"),
                        ],
                        max_length=5,
                    ),
                ),
                ("name", models.TextField()),
                ("number", models.CharField(blank=True, max_length=10)),
                ("thumnail", models.TextField(blank=True, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("contact", models.TextField(blank=True)),
                ("realtime", models.TextField(blank=True)),
                ("performance", models.BooleanField(default=False)),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="booths", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("menu", models.TextField()),
                ("price", models.PositiveIntegerField()),
                ("is_soldout", models.BooleanField(default=False)),
                ("img", models.TextField(blank=True, null=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="booths.booth",
                    ),
                ),
                (
                    "like",
                    models.ManyToManyField(
                        blank=True, related_name="menus", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[("수요일", "수요일"), ("목요일", "목요일"), ("금요일", "금요일")],
                        max_length=5,
                    ),
                ),
                ("date", models.IntegerField(choices=[(8, 8), (9, 9), (10, 10)])),
                ("start_time", models.CharField(max_length=5)),
                ("end_time", models.CharField(max_length=5)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="booths.booth",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="booths.booth",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
