# Generated by Django 4.2.7 on 2024-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booths", "0002_auto_20240501_0038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="category",
            field=models.CharField(
                choices=[
                    ("음식", "음식"),
                    ("굿즈", "굿즈"),
                    ("체험", "체험"),
                    ("댄스", "댄스"),
                    ("밴드", "밴드"),
                    ("노래", "노래"),
                    ("연주", "연주"),
                    ("기타", "기타"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="booth",
            name="contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booth",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booth",
            name="opened",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="booth",
            name="realtime",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="realtime",
            field=models.TextField(blank=True, null=True),
        ),
    ]
